image:
  repository: gdiamos/scalarlm-amd
  tag: v0.997
  pullPolicy: Always

service:
  type: ClusterIP
  api_port: 8000
  vllm_port: 8001
  externalIP: 64.139.222.102

jobs_pvc:
  storageClass: longhorn
  size: 100Gi

cache_pvc:
  storageClass: longhorn
  size: 400Gi

slurm_config_pvc:
    storageClass: longhorn
    size: 10Gi

cloudflared:
  tunnelToken: eyJhIjoiMDhmMjU0OGRjYWJmOGJhNDI0Y2M2ZTY0MDdkYmQzZDQiLCJ0IjoiNjFkNmVmYjYtOWZiZS00NmNjLWIyOWEtZDk1ODY4ZjE2NDE2IiwicyI6Ik5HWm1ORFZtWW1JdE5HWTBZeTAwWW1ObExXRTFaREl0WVRZek1qQXpNRGM1WWpBNCJ9

model: Qwen/Qwen3-235B-A22B-Instruct-2507
max_model_length: 32768
gpu_memory_utilization: 0.95
dtype: bfloat16

training_replicas: 0
inference_replicas: 1
api_replicas: 1
tensor_parallel_size: 4

max_train_time: 86400
