image:
  repository: nailafarooqui/scalarlm-amd-gfx942
  tag: v0.997
  pullPolicy: Always

service:
  type: ClusterIP
  api_port: 8000
  vllm_port: 8001
  externalIP: 64.139.222.102

jobs_pvc:
  storageClass: local-path
  size: 100Gi

cache_pvc:
  storageClass: local-path
  size: 400Gi

slurm_config_pvc:
    storageClass: local-path
    size: 10Gi

cloudflared:
  tunnelToken: eyJhIjoiNTFhYzZjZDk4NjNiZDEwODhjMDQ0MWY1NzdmNGFlNGYiLCJ0IjoiZWU2ZmZjMTMtZThjNS00NWI1LWEwZjUtZDc5OTZkZTZjZTAxIiwicyI6Ik56QXhPR1JoTlRrdE1tSXdOaTAwTTJFeUxUazROek10Tnpoa1lUbGpNemMwWXpVMSJ9

model: Qwen/Qwen3-235B-A22B-Instruct-2507
max_model_length: 32768
gpu_memory_utilization: 0.95
dtype: bfloat16

training_replicas: 0
inference_replicas: 1
tensor_parallel_size: 4

max_train_time: 86400
